name: Build and Release

on:
  push:
    tags:
      - "v*"  # v로 시작하는 태그 발생 시 실행
  workflow_dispatch:  # 수동 실행 가능

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up variables
        run: echo "RELEASE_NAME=$(basename ${{ github.ref }})" >> $GITHUB_ENV

      - name: Zip source code
        run: |
          zip -r mapae-${{ env.RELEASE_NAME }}.zip . -x "*.git*"

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: mapae-${{ env.RELEASE_NAME }}.zip
          path: mapae-${{ env.RELEASE_NAME }}.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: mapae-${{ env.RELEASE_NAME }}.zip
          tag_name: ${{ env.RELEASE_NAME }}
          release_name: Release ${{ env.RELEASE_NAME }}
          body: "자동 배포된 릴리즈"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


