name: Build and Upload to Google Drive

on:
  push:
    tags:
      - "v*"  # v로 시작하는 태그 발생 시 실행
  workflow_dispatch:  # 수동 실행 가능

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up variables
        run: echo "RELEASE_NAME=$(basename ${{ github.ref }})" >> $GITHUB_ENV

      - name: Zip source code
        run: |
          zip -r mapae-${{ env.RELEASE_NAME }}.zip . -x "*.git*"

      - name: Upload artifact to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: mapae-${{ env.RELEASE_NAME }}.zip
          tag_name: ${{ env.RELEASE_NAME }}
          name: Release ${{ env.RELEASE_NAME }}
          body: "자동 배포된 릴리즈"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  upload-to-drive:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Release Asset
        uses: dsaltares/fetch-gh-release-asset@v1
        with:
          repo: ${{ github.repository }}
          version: "tags/${{ github.ref_name }}"
          file: "mapae-${{ github.ref_name }}.zip"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload to Google Drive
        uses: robinraju/gdrive-action@v0.3
        with:
          service_account_key: ${{ secrets.GDRIVE_JSON_KEY }}
          folder_id: "YOUR_GOOGLE_DRIVE_FOLDER_ID"
          file: "mapae-${{ github.ref_name }}.zip"
